### PR TITLE
Refactor dir path argument validity checks

### PR DESCRIPTION
**Pull request by chrissimpkins**
A bit more idiomatic approach...

### CODE REVIEW

**Comment by madig** [comment]
The checking could also be rolled into `format_ufo`, i.e. check there and return an error. Saves you an extra loop!

**Comment by chrissimpkins** [comment]
> The checking could also be rolled into `format_ufo`, i.e. check there and return an error. Saves you an extra loop!

Process good paths and collect those errors to report out the ones that had bad paths rather than short circuiting all formatting execution if there are any bad paths?

**Comment by madig** [comment]
Yes 😁

**Comment by chrissimpkins** [comment]
I think that I may refactor this PR to a lib so that we can begin to add tests around the non-norad stuff.  Or just add it in norad and catch the errors here.  Thinking.

**Comment by chrissimpkins** [comment]
New approach as of dc6875990262656f289b2e50d88de3257d656c20

Refactored to library, addressed Nikolaus's recommendation in https://github.com/source-foundry/ufofmt/pull/5#issuecomment-885942538, handle norad lib errors with the addition of UFO paths and read/write status of the error, added a couple of new custom types as QOL changes for the error handling.

**Comment by madig** [comment]
Hm, you may want to lean more on Rust for the errors. You can make your own error container like https://github.com/linebender/norad/blob/master/src/error.rs#L11-L47 and then implement Display for it for formatting them for printing: https://github.com/linebender/norad/blob/master/src/error.rs#L150-L201

**Comment by chrissimpkins** [comment]
> Hm, you may want to lean more on Rust for the errors. You can make your own error container like https://github.com/linebender/norad/blob/master/src/error.rs#L11-L47 and then implement Display for it for formatting them for printing: https://github.com/linebender/norad/blob/master/src/error.rs#L150-L201

👍 #11

**Pull request merged**
